import subprocess
import json
import asyncio
from schemas import Plan

# Using 3.2:3b for stability on this machine
OLLAMA_MODEL = "llama3.2:3b"

SYSTEM_PROMPT = """
You are TITAN Planner.
You do NOT execute actions.
You ONLY produce a safe, execution-ready JSON PLAN for the Runner.

AVAILABLE TOOLS:
- http.get(url: str): Fetch a webpage (HTML).
- browser.open(url: str): Open a URL in the user's visible browser window.
- file.write(path: str, content: str): Save a report, code, or artifact.
- python.run(script: str): Run a python script (Sandboxed).
- file.read(path: str): Read a file.

Output STRICT JSON.
No prose. No markdown.
"""

def generate_plan(task_id: str, goal: str, context: dict) -> dict:
    try:
        # Send raw text prompt, not JSON object, to avoid confusion
        actual_prompt = f"""
SYSTEM:
{SYSTEM_PROMPT}

INTENT MAPPING:
- "Search", "Browse", "Go to" -> Use 'http.get(url)'
- "List", "Save" -> Use 'http.get' then 'file.write'
- "Open" -> Use 'browser.open(url)'

GOAL:
{goal}

CONTEXT:
{json.dumps(context, indent=2)}

IMPORTANT: Return VALID JSON.
Required keys: "task_id", "goal", "steps".
"steps" must be an array of objects with "tool" and "action".

EXAMPLE:
{{
  "task_id": "{task_id}",
  "goal": "{goal}",
  "steps": [
    {{ "step_id": "1", "tool": "http.get", "action": {{ "url": "..." }} }}
  ]
}}
"""
        proc = subprocess.run(
            ["ollama", "run", OLLAMA_MODEL],
            input=actual_prompt,
            capture_output=True,
            text=True,
            timeout=120,
            encoding='utf-8'
        )
        
        if proc.returncode != 0:
            err = proc.stderr
            print(f"Ollama Error: {err}")
            return _fallback_plan(task_id, goal, f"Ollama Failed: {err}")

        raw = proc.stdout.strip()
        
        # Clean Markdown
        if "```json" in raw:
            raw = raw.split("```json")[1].split("```")[0].strip()
        elif "```" in raw:
            raw = raw.split("```")[1].split("```")[0].strip()

        data = json.loads(raw)
        
        # Schema Validation
        if "steps" not in data or not isinstance(data["steps"], list):
            raise ValueError("Planner output missing 'steps' array")

        return data

    except Exception as e:
        print(f"Planner Exception: {e}")
        return _fallback_plan(task_id, goal, f"Planner Exception: {str(e)}")

def _fallback_plan(task_id, goal, error_msg):
    # Safe fallback so the system doesn't crash 500
    return {
        "task_id": task_id,
        "goal": goal,
        "steps": [
            {
                "step_id": "fallback_step_1",
                "tool": "file.write",
                "action": {
                    "path": "TITAN/io/outbox/error_report.txt",
                    "content": f"Planner Failed for Goal: {goal}\nError: {error_msg}\n\n(Auto-generated by Fallback)"
                }
            }
        ],
        "success_criteria": ["Reported Error"]
    }
