-- ReachX Dormitories schema
-- Run this in Supabase SQL editor for project abkprecmhitqmmlzxfad

create table if not exists public.dormitories (
    id                  bigint generated by default as identity primary key,
    name                text        not null,
    owner_name          text,
    contact_phone       text,
    contact_email       text,
    country             text        not null default 'Mauritius',
    city                text,
    area                text,
    capacity_total      integer,
    capacity_occupied   integer,
    gender              text, -- Male / Female / Mixed
    notes               text,
    created_at          timestamptz not null default now()
);

create index if not exists idx_dormitories_name_lower
    on public.dormitories (lower(name));

create index if not exists idx_dormitories_city_gender
    on public.dormitories (city, gender);
