$projectRoot = 'F:\ReachX-AI'
$schemaDir   = Join-Path $projectRoot 'schema'
$scriptsDir  = Join-Path $projectRoot 'scripts'
$dataDir     = Join-Path $projectRoot 'data\normalised'

foreach ($d in @($schemaDir, $scriptsDir, $dataDir)) {
    if (-not (Test-Path $d)) {
        New-Item -Path $d -ItemType Directory -Force | Out-Null
    }
}

# 1) SCHEMA FILE (employers + agents)
$schemaPath = Join-Path $schemaDir 'reachx-employers-agents-schema.sql'

$schemaSql = @'
-- ReachX Employers + Agents schema
-- Run this in Supabase SQL editor for project abkprecmhitqmmlzxfad

create table if not exists public.employers (
    id                      bigint generated by default as identity primary key,
    company_name            text        not null,
    contact_name            text,
    contact_email           text,
    contact_phone           text,
    country                 text,
    city                    text,
    sector                  text,
    headcount_estimate      integer,
    notes                   text,
    created_at              timestamptz not null default now()
);

create index if not exists idx_employers_company_lower
    on public.employers (lower(company_name));

create index if not exists idx_employers_country_sector
    on public.employers (country, sector);

create table if not exists public.agents (
    id                      bigint generated by default as identity primary key,
    agency_name             text        not null,
    country                 text        not null,
    city                    text,
    contact_name            text,
    contact_email           text,
    contact_phone           text,
    whatsapp                text,
    lanes                   text, -- e.g. 'India→Mauritius,Nepal→Mauritius'
    status                  text    not null default 'active',
    notes                   text,
    created_at              timestamptz not null default now()
);

create index if not exists idx_agents_agency_lower
    on public.agents (lower(agency_name));

create index if not exists idx_agents_country_status
    on public.agents (country, status);
'@

Set-Content -Path $schemaPath -Value $schemaSql -Encoding UTF8
Write-Host "Schema file created at: $schemaPath" -ForegroundColor Green

# 2) SAMPLE CSVs

$employersCsvPath = Join-Path $dataDir 'employers-normalised.csv'
$agentsCsvPath    = Join-Path $dataDir 'agents-normalised.csv'

$employers = @(
    [pscustomobject]@{
        company_name       = 'OceanView Resorts Ltd'
        contact_name       = 'Anjali Sharma'
        contact_email      = 'hr@oceanview.mu'
        contact_phone      = '+2302010001'
        country            = 'Mauritius'
        city               = 'Flic-en-Flac'
        sector             = 'Hospitality'
        headcount_estimate = 250
        notes              = 'Needs chefs, kitchen staff, housekeeping for peak season'
    },
    [pscustomobject]@{
        company_name       = 'Port Louis Construction Co'
        contact_name       = 'Jean-Pierre Didier'
        contact_email      = 'hr@plcc.mu'
        contact_phone      = '+2302080002'
        country            = 'Mauritius'
        city               = 'Port Louis'
        sector             = 'Construction'
        headcount_estimate = 180
        notes              = 'Ongoing demand for masons, carpenters, welders'
    }
)

$employers | Export-Csv -Path $employersCsvPath -NoTypeInformation -Encoding UTF8
Write-Host "Sample employers CSV: $employersCsvPath" -ForegroundColor Green

$agents = @(
    [pscustomobject]@{
        agency_name   = 'Bharat SkillLink'
        country       = 'India'
        city          = 'Mumbai'
        contact_name  = 'Ravi Kumar'
        contact_email = 'ravi@bharatskilllink.in'
        contact_phone = '+91-9988776655'
        whatsapp      = '+91-9988776655'
        lanes         = 'India→Mauritius'
        status        = 'active'
        notes         = 'Strong pipeline for hospitality + F&B workers'
    },
    [pscustomobject]@{
        agency_name   = 'Himalayan Workforce Pvt Ltd'
        country       = 'Nepal'
        city          = 'Kathmandu'
        contact_name  = 'Sushmita Thapa'
        contact_email = 'sushmita@himalayanworkforce.com'
        contact_phone = '+977-9812345678'
        whatsapp      = '+977-9812345678'
        lanes         = 'Nepal→Mauritius'
        status        = 'active'
        notes         = 'Focus on construction and security staff'
    }
)

$agents | Export-Csv -Path $agentsCsvPath -NoTypeInformation -Encoding UTF8
Write-Host "Sample agents CSV: $agentsCsvPath" -ForegroundColor Green

# 3) PUBLISHERS

$pubEmployersPath = Join-Path $scriptsDir 'Publish-ReachXEmployersToSupabase.ps1'
$pubAgentsPath    = Join-Path $scriptsDir 'Publish-ReachXAgentsToSupabase.ps1'

$pubEmployers = @'
param(
    [string]$CsvPath     = "F:\ReachX-AI\data\normalised\employers-normalised.csv",
    [string]$SupabaseUrl = $env:REACHX_SUPABASE_URL,
    [string]$SupabaseKey = $env:REACHX_SUPABASE_SERVICE_KEY
)

if (-not (Test-Path $CsvPath)) {
    Write-Host "CSV not found: $CsvPath" -ForegroundColor Red
    return
}
if (-not $SupabaseUrl -or -not $SupabaseKey) {
    Write-Host "Supabase URL or Key missing in environment." -ForegroundColor Red
    return
}

$base      = $SupabaseUrl.TrimEnd("/")
$deleteUri = "$base/rest/v1/employers?id=not.is.null"
$insertUri = "$base/rest/v1/employers"

$deleteHeaders = @{
    apikey        = $SupabaseKey
    Authorization = "Bearer $SupabaseKey"
    Prefer        = "return=representation"
}
$insertHeaders = @{
    apikey         = $SupabaseKey
    Authorization  = "Bearer $SupabaseKey"
    "Content-Type" = "application/json"
    Prefer         = "return=representation"
}

Write-Host "Publishing employers from: $CsvPath" -ForegroundColor Cyan
Write-Host "→ Insert endpoint: $insertUri" -ForegroundColor Cyan

try {
    Write-Host "Clearing ALL rows in public.employers via: $deleteUri" -ForegroundColor Yellow
    Invoke-RestMethod -Uri $deleteUri -Headers $deleteHeaders -Method Delete | Out-Null
}
catch {
    Write-Host "Warning: failed to clear employers table: $($_.Exception.Message)" -ForegroundColor DarkYellow
}

$rows = Import-Csv -Path $CsvPath
if (-not $rows -or $rows.Count -eq 0) {
    Write-Host "No employers found in CSV." -ForegroundColor Yellow
    return
}

function Trim-Value {
    param($v)
    if ($null -eq $v) { return $null }
    $t = $v.ToString().Trim()
    if ($t -eq "") { return $null }
    return $t
}

$success = 0; $fail = 0

foreach ($r in $rows) {
    $body = [pscustomobject]@{
        company_name       = Trim-Value $r.company_name
        contact_name       = Trim-Value $r.contact_name
        contact_email      = Trim-Value $r.contact_email
        contact_phone      = Trim-Value $r.contact_phone
        country            = Trim-Value $r.country
        city               = Trim-Value $r.city
        sector             = Trim-Value $r.sector
        headcount_estimate = if ($r.headcount_estimate) { [int]$r.headcount_estimate } else { $null }
        notes              = Trim-Value $r.notes
    }

    if ([string]::IsNullOrWhiteSpace($body.company_name)) { continue }

    $json = $body | ConvertTo-Json -Depth 4
    try {
        $resp = Invoke-RestMethod -Uri $insertUri -Headers $insertHeaders -Method Post -Body "[$json]"
        $success++
        Write-Host "OK   -> $($body.company_name) [$($body.sector)]" -ForegroundColor Green
    }
    catch {
        $fail++
        Write-Host "FAIL -> $($body.company_name): $($_.Exception.Message)" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "Employers — Done. Success: $success | Failed: $fail" -ForegroundColor Cyan
'@

Set-Content -Path $pubEmployersPath -Value $pubEmployers -Encoding UTF8
Write-Host "Employers publisher: $pubEmployersPath" -ForegroundColor Green

$pubAgents = @'
param(
    [string]$CsvPath     = "F:\ReachX-AI\data\normalised\agents-normalised.csv",
    [string]$SupabaseUrl = $env:REACHX_SUPABASE_URL,
    [string]$SupabaseKey = $env:REACHX_SUPABASE_SERVICE_KEY
)

if (-not (Test-Path $CsvPath)) {
    Write-Host "CSV not found: $CsvPath" -ForegroundColor Red
    return
}
if (-not $SupabaseUrl -or -not $SupabaseKey) {
    Write-Host "Supabase URL or Key missing in environment." -ForegroundColor Red
    return
}

$base      = $SupabaseUrl.TrimEnd("/")
$deleteUri = "$base/rest/v1/agents?id=not.is.null"
$insertUri = "$base/rest/v1/agents"

$deleteHeaders = @{
    apikey        = $SupabaseKey
    Authorization = "Bearer $SupabaseKey"
    Prefer        = "return=representation"
}
$insertHeaders = @{
    apikey         = $SupabaseKey
    Authorization  = "Bearer $SupabaseKey"
    "Content-Type" = "application/json"
    Prefer         = "return=representation"
}

Write-Host "Publishing agents from: $CsvPath" -ForegroundColor Cyan
Write-Host "→ Insert endpoint: $insertUri" -ForegroundColor Cyan

try {
    Write-Host "Clearing ALL rows in public.agents via: $deleteUri" -ForegroundColor Yellow
    Invoke-RestMethod -Uri $deleteUri -Headers $deleteHeaders -Method Delete | Out-Null
}
catch {
    Write-Host "Warning: failed to clear agents table: $($_.Exception.Message)" -ForegroundColor DarkYellow
}

$rows = Import-Csv -Path $CsvPath
if (-not $rows -or $rows.Count -eq 0) {
    Write-Host "No agents found in CSV." -ForegroundColor Yellow
    return
}

function Trim-Value {
    param($v)
    if ($null -eq $v) { return $null }
    $t = $v.ToString().Trim()
    if ($t -eq "") { return $null }
    return $t
}

$success = 0; $fail = 0

foreach ($r in $rows) {
    $body = [pscustomobject]@{
        agency_name   = Trim-Value $r.agency_name
        country       = Trim-Value $r.country
        city          = Trim-Value $r.city
        contact_name  = Trim-Value $r.contact_name
        contact_email = Trim-Value $r.contact_email
        contact_phone = Trim-Value $r.contact_phone
        whatsapp      = Trim-Value $r.whatsapp
        lanes         = Trim-Value $r.lanes
        status        = Trim-Value $r.status
        notes         = Trim-Value $r.notes
    }

    if ([string]::IsNullOrWhiteSpace($body.agency_name)) { continue }

    $json = $body | ConvertTo-Json -Depth 4
    try {
        $resp = Invoke-RestMethod -Uri $insertUri -Headers $insertHeaders -Method Post -Body "[$json]"
        $success++
        Write-Host "OK   -> $($body.agency_name) [$($body.country)]" -ForegroundColor Green
    }
    catch {
        $fail++
        Write-Host "FAIL -> $($body.agency_name): $($_.Exception.Message)" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "Agents — Done. Success: $success | Failed: $fail" -ForegroundColor Cyan
'@

Set-Content -Path $pubAgentsPath -Value $pubAgents -Encoding UTF8
Write-Host "Agents publisher: $pubAgentsPath" -ForegroundColor Green

Write-Host "`nNEXT:" -ForegroundColor Yellow
Write-Host "1) In Supabase SQL editor, run:  $schemaPath" -ForegroundColor Yellow
Write-Host "2) In PowerShell:" -ForegroundColor Yellow
Write-Host '   & "F:\ReachX-AI\scripts\Load-ReachXSupabase.ps1"' -ForegroundColor Yellow
Write-Host '   & "F:\ReachX-AI\scripts\Publish-ReachXEmployersToSupabase.ps1"' -ForegroundColor Yellow
Write-Host '   & "F:\ReachX-AI\scripts\Publish-ReachXAgentsToSupabase.ps1"' -ForegroundColor Yellow
