-- F:\AION-ZERO\state\az_commands.ddl.sql
-- Run this ONCE in Supabase SQL editor for project: abkprecmhitqmmlzxfad

create table if not exists public.az_commands (
  id            bigint generated by default as identity primary key,
  project       text        not null default 'AION-ZERO',
  target_agent  text        not null,
  command       text        not null,
  args          jsonb       not null default '{}'::jsonb,
  status        text        not null default 'pending', -- pending|processing|done|error
  created_at    timestamptz not null default now(),
  picked_at     timestamptz,
  completed_at  timestamptz,
  error         text
);

create index if not exists idx_az_commands_status_created
  on public.az_commands(status, created_at);
