import json
import subprocess
import argparse
from pathlib import Path
import sys

# Paths (relative to project root usually)
PROJECT_ROOT = Path(__file__).resolve().parents[1]
UTILS_PATH = Path("F:/AION-ZERO/TITAN/apps/utils/summarize_cli.py")

def generate_report(data_file: Path, output_dir: Path):
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Ingest
    ingest_script = PROJECT_ROOT / "src" / "ingest.py"
    ingest_out = output_dir / "ingest_result.json"
    
    print(f"[REPORT] Running Ingest on {data_file}...")
    run_ingest = subprocess.run(
        ["python", str(ingest_script), "--in", str(data_file), "--out", str(ingest_out)],
        capture_output=True, text=True
    )
    
    if run_ingest.returncode != 0:
        print(f"[FAIL] Ingest failed: {run_ingest.stderr}")
        return
        
    ingest_data = json.loads(ingest_out.read_text(encoding="utf-8"))
    if not ingest_data.get("ok"):
        print(f"[FAIL] Ingest Error: {ingest_data.get('error')}")
        return

    # 2. Summarize (Ollama)
    llm_text = ingest_data["llm_text"]
    context_file = output_dir / "context.txt"
    context_file.write_text(llm_text, encoding="utf-8")
    
    summary_out = output_dir / "summary_result.json"
    print(f"[REPORT] Running AI Summarizer...")
    
    run_ai = subprocess.run(
        ["python", str(UTILS_PATH), "--in", str(context_file), "--out", str(summary_out), "--llm", "qwen2.5-coder:7b"],
        capture_output=True, text=True # Using capture_output to keep console clean
    )
    
    if run_ai.returncode != 0:
        print(f"[FAIL] AI Summarizer failed: {run_ai.stderr}")
        # Proceeding without AI summary is possible but let's fail for now
        return

    ai_data = json.loads(summary_out.read_text(encoding="utf-8"))
    ai_findings = ai_data.get("findings", {})
    
    # 3. Render Final Report
    metrics = ingest_data["metrics"]
    report_md = f"""# Monthly Grant Report

**Date Generated:** {ingest_data.get("entries", [{}])[0].get("date", "N/A")}
**Generated By:** TITAN NGO Automator

## 1. Executive Summary
{ai_findings.get("summary", "No summary generated.")}

### Key Highlights
"""
    for bull in ai_findings.get("bullets", []):
        report_md += f"- {bull}\n"

    report_md += f"""
## 2. Financial Overview
| Metric | Value |
| :--- | :--- |
| **Total Spent** | {metrics['total_spent']:,.2f} {metrics['currency']} |
| **Pending** | {metrics['total_pending']:,.2f} {metrics['currency']} |
| **Activities** | {metrics['count']} |

## 3. Risks & Actions
"""
    for risk in ai_findings.get("risks", []):
        report_md += f"- ⚠️ {risk}\n"
        
    report_md += "\n"
    for act in ai_findings.get("actions", []):
        report_md += f"- ✅ {act}\n"

    final_report = output_dir / "Final_Report.md"
    final_report.write_text(report_md, encoding="utf-8")
    
    print(f"[SUCCESS] Report generated at: {final_report}")
    print(report_md)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True, help="Input CSV")
    ap.add_argument("--out", default="output", help="Output directory")
    args = ap.parse_args()
    
    generate_report(Path(args.data), Path(args.out))

if __name__ == "__main__":
    main()
