import json
import argparse
from pathlib import Path

def render_report(analysis_path: Path, output_path: Path):
    print(f"[REPORT] Rendering {analysis_path}...")
    
    if not analysis_path.exists():
        print("[FAIL] Analysis file missing")
        return
        
    data = json.loads(analysis_path.read_text(encoding="utf-8"))
    
    score = data.get("risk_score", 0)
    level = data.get("risk_level", "UNKNOWN")
    findings = data.get("findings", [])
    
    # Verdict Logic
    verdict = "✅ APPROVED"
    color = "green"
    if level == "MEDIUM": verdict = "⚠️ REVIEW REQUIRED"; color = "orange"
    if level in ["HIGH", "CRITICAL"]: verdict = "🛑 REJECT / LEGAL REVIEW"; color = "red"
    
    md = f"""# ⚖️ Contract Risk Verdict

**Verdict:** {verdict}
**Risk Level:** {level} (Score: {score})
**Clauses Analyzed:** {data.get("clause_count_analyzed", 0)}

## 🚩 Red Flags Detected
"""
    
    if not findings:
        md += "_No major red flags detected._\n"
    else:
        for f in findings:
            md += f"- **{f['type'].upper()}**: {f['warning']} (Impact: {f['impact']})\n"
            
    md += """
## 📝 Recommendations
1. Negotiate caps on liability.
2. Verify indemnity reciprocity.
3. Ensure termination clauses require reasonable notice.

---
*Generated by TITAN Agreement Risk Engine*
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(md, encoding="utf-8")
    print(f"[SUCCESS] Report saved to {output_path}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True)
    ap.add_argument("--out", dest="out", required=True)
    args = ap.parse_args()
    
    render_report(Path(args.inp), Path(args.out))

if __name__ == "__main__":
    main()
