import { Employee, Deduction, PayrollPeriod, PayrollEntry } from '@/types/payroll';

export const initialEmployees: Employee[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@company.com',
    phone: '(555) 123-4567',
    department: 'Engineering',
    position: 'Senior Developer',
    hireDate: '2022-03-15',
    employmentType: 'full-time',
    payType: 'salary',
    payRate: 120000,
    status: 'active',
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@company.com',
    phone: '(555) 234-5678',
    department: 'Marketing',
    position: 'Marketing Manager',
    hireDate: '2021-06-01',
    employmentType: 'full-time',
    payType: 'salary',
    payRate: 95000,
    status: 'active',
  },
  {
    id: '3',
    firstName: 'Mike',
    lastName: 'Williams',
    email: 'mike.williams@company.com',
    phone: '(555) 345-6789',
    department: 'Sales',
    position: 'Sales Representative',
    hireDate: '2023-01-10',
    employmentType: 'full-time',
    payType: 'hourly',
    payRate: 35,
    hoursPerWeek: 40,
    status: 'active',
  },
  {
    id: '4',
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emily.brown@company.com',
    phone: '(555) 456-7890',
    department: 'HR',
    position: 'HR Specialist',
    hireDate: '2022-09-20',
    employmentType: 'full-time',
    payType: 'salary',
    payRate: 65000,
    status: 'active',
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Davis',
    email: 'david.davis@company.com',
    phone: '(555) 567-8901',
    department: 'Engineering',
    position: 'Junior Developer',
    hireDate: '2023-07-01',
    employmentType: 'part-time',
    payType: 'hourly',
    payRate: 25,
    hoursPerWeek: 20,
    status: 'active',
  },
];

export const defaultDeductions: Deduction[] = [
  {
    id: 'fed-tax',
    name: 'Federal Tax',
    type: 'percentage',
    amount: 12,
    category: 'tax',
  },
  {
    id: 'state-tax',
    name: 'State Tax',
    type: 'percentage',
    amount: 5,
    category: 'tax',
  },
  {
    id: 'social-security',
    name: 'Social Security',
    type: 'percentage',
    amount: 6.2,
    category: 'tax',
  },
  {
    id: 'medicare',
    name: 'Medicare',
    type: 'percentage',
    amount: 1.45,
    category: 'tax',
  },
  {
    id: 'health-insurance',
    name: 'Health Insurance',
    type: 'fixed',
    amount: 200,
    category: 'insurance',
  },
  {
    id: '401k',
    name: '401(k)',
    type: 'percentage',
    amount: 5,
    category: 'retirement',
  },
];

export const departments = [
  'Engineering',
  'Marketing',
  'Sales',
  'HR',
  'Finance',
  'Operations',
  'Customer Service',
];

export const positions = [
  'CEO',
  'CTO',
  'CFO',
  'Senior Developer',
  'Junior Developer',
  'Marketing Manager',
  'Sales Representative',
  'HR Specialist',
  'Accountant',
  'Operations Manager',
];