name: AION-ZERO Guardrails CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install cyclonedx-bom

      - name: SBOM (CycloneDX)
        run: |
          cyclonedx-py --format json -o out/sbom.cdx.json || true

      - name: License/Similarity Scan (placeholder)
        run: |
          echo "Run your license scanner here"

      - name: Secret/Migration Guard (placeholder)
        run: |
          echo "Fail if code touches forbidden paths"

      - name: Tests
        run: |
          echo "Run unit/api/ui tests here"; exit 0
