import os
import sys
import psycopg2
from urllib.parse import urlparse

# Load env manually or rely on python-dotenv? 
# We'll just parse the conn string from args or assume set by caller
# But caller is PowerShell which loads .env... wait.
# PowerShell sets process env, so os.environ should have it IF passed.
# But Start-Process in PS might not pass env unless specified?
# If I run "python Fix-Db.py", it inherits current process env.
# In PS: $env:VAR is set. Python sees os.environ["VAR"].

DB_URL = os.environ.get("JARVIS_DB_CONN")

if not DB_URL:
    # Fallback: try to read .env
    try:
        with open(r"F:\AION-ZERO\.env", "r") as f:
            for line in f:
                if line.startswith("JARVIS_DB_CONN="):
                    DB_URL = line.split("=", 1)[1].strip()
                    break
    except Exception as e:
        print(f"Error reading .env: {e}")

if not DB_URL:
    print("CRITICAL: JARVIS_DB_CONN not found.")
    sys.exit(1)

print(f"Connecting to DB...")

try:
    conn = psycopg2.connect(DB_URL)
    conn.autocommit = True
    cur = conn.cursor()
    
    # 1. Create az_agent_runs if missing
    print("Checking az_agent_runs...")
    cur.execute("""
        CREATE TABLE IF NOT EXISTS public.az_agent_runs (
            id bigint generated by default as identity not null primary key,
            created_at timestamp with time zone not null default now(),
            agent text not null,
            command_id bigint,
            status text not null,
            payload jsonb,
            duration_ms int
        );
    """)
    print("Table ensured.")

    # 2. Grant permissions
    print("Granting permissions...")
    cur.execute("GRANT ALL ON TABLE public.az_agent_runs TO postgres, anon, authenticated, service_role;")
    
    # 3. Reload Schema Cache
    print("Reloading Schema Cache...")
    cur.execute("NOTIFY pgrst, 'reload schema';")
    print("Done.")

    cur.close()
    conn.close()

except Exception as e:
    print(f"DB Error: {e}")
    sys.exit(1)
